apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetook2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetook2
  template:
    metadata:
      labels:
        app: tetook2
    spec:
      containers:
      - image: okteto.dev/tetook2:latest
        name: tetook2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "16218704-e4e3-4097-ac5a-9538b3b70c65"
        - name: Vless_Path
          value: "/jjuht6tg"
        - name: Vmess_UUID
          value: "c61904aa-0463-4123-af0d-ce1412da0856"
        - name: Vmess_Path
          value: "/u7nnt5fguk"
        - name: Share_Path
          value: "/v2link"
