apiVersion: v1
kind: Service
metadata:
  name: tetook2
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tetook2"
    port: 8080
  selector:
    app: tetook2
